name: Visit Website Twice Daily at Greek Time

on:
  schedule:
    - cron: '0 4 * * *'   # 07:00 EEST (4:00 UTC)
    - cron: '0 13 * * *'  # 16:00 EEST (13:00 UTC)

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run visit script
        run: python visit_website.py
