name: Visit Website

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC (adjust as needed)

jobs:
  visit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run visit script
        run: python visit_website.py
